import type { Metadata } from "next";
import { Poppins as Font } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { cn } from "../lib/utils";
import Navbar from "../components/Navbar/Navbar";

const font = Font({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Timemachines - wypożyczalnia aut",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <Toaster position="bottom-right" richColors expand={true} />
      <body
        className={cn(font.className, "relative h-full font-sans antialiased")}
      >
        <main className="relative flex flex-col min-h-screen">
          <Navbar />
          <div className="flex-grow flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
